### ISSUE TITLE
can not run android/ios when add plugin "react-native-plugin-pollfish"

### ISSUE THREAD

**Issue by HarveyNgo** [pollfish/react-native-plugin-pollfish#2]
I try to install lib "react-native-plugin-pollfish" follow your instruction

and I did run "react-native link react-native-plugin-pollfish"

For android:

I can run on emulator , but when I add 
var params = new RNPollfish.Builder('key')
      .indicatorPosition(RNPollfish.Position.topLeft)
      .indicatorPadding(10)
      .offerwallMode(true)
      .rewardMode(false)
      .releaseMode(false)
      .requestUUID('UUID')
      .userProperties({
        gender: '1',
        education: '1'
      })
      .build();

    RNPollfish.init(params);

Android appear error like this screen:
<a href="https://ibb.co/RDZSzVX"><img src="https://i.ibb.co/YLYWpq5/Screen-Shot-2021-06-02-at-4-31-25-PM.png" alt="Screen-Shot-2021-06-02-at-4-31-25-PM" border="0"></a><br /><a target='_blank' href='https://vi.imgbb.com/'>ảnh free</a><br />

For IOS, I can not run  and appear this error:

** BUILD FAILED **

The following build commands failed:
***********************************
CompileC /Users/ngovihung/Library/Developer/Xcode/DerivedData/ChatTee-aofpgqtlbbwyrqaqtmdyqhzrekyf/Build/Intermediates.noindex/RNPollfish.build/Debug-iphonesimulator/RNPollfish.build/Objects-normal/x86_64/RNPollfish.o /Users/ngovihung/Documents/Projects/chattee_react_native/node_modules/react-native-plugin-pollfish/ios/RNPollfish.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

***********************************

**Comment by fotism23** [comment]
Hello @HarveyNgo 

Thanks for the report.

We have just released v1.0.1 which fixes iOS-podspec related issue and we recommend to update your react-native-plugin-pollfish to latest.

Regarding the Android issue it seems to be documentation issue regarding RNPollfish.Builder usage.

Please try to refactor your initialization code to:

```js
var params = new RNPollfish.Builder('key');

params
  .indicatorPosition(RNPollfish.Position.topLeft)
  .indicatorPadding(10)
  .offerwallMode(true)
  .rewardMode(false)
  .releaseMode(false)
  .requestUUID('UUID')
  .userProperties({
    gender: '1',
    education: '1'
  })
  .build();
```

**Comment by HarveyNgo** [comment]
Dear @fotism23 ,
The issue still happen
do I need to manually integrate pollfish to Xcode?

OS: macOS Big Sur version 11.3
Xcode: 12.5

I send u the full log when run ios
[errorLog.txt](https://github.com/pollfish/react-native-plugin-pollfish/files/6595809/errorLog.txt)

**Comment by fotism23** [comment]
Did you run `pod install` inside the generate ios directory?

**Comment by HarveyNgo** [comment]
> Did you run `pod install` inside the generated ios directory?

yes, I tried eveything, remove node_modules, remove podfile.lock, "pod install --repo-update" also tried
still no hope

**Comment by fotism23** [comment]
Which version of react-native-plugin-pollfish and node you are using?

**Comment by HarveyNgo** [comment]
> react-native-plugin-pollfish

 "react-native-plugin-pollfish": "^1.0.1",
 "react-native": "0.61.5",

**Comment by fotism23** [comment]
Please reach out to fotis@pollfish.com, so we can arrange a call and review your integration.

**Comment by HarveyNgo** [comment]
I fix the issue, I have to upgrade cocoapods to version "1.10.1"
